# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duckmigrate < Formula
  desc "Database migrations for DuckDB, as a Go library and a Cobra CLI."
  homepage "https://github.com/mrfoh/duckmigrate"
  version "1.0.0-rc-6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrfoh/duckmigrate/releases/download/v1.0.0-rc-6/duckmigrate-v1.0.0-rc-6_darwin_amd64.tar.gz"
      sha256 "42e25652b45eef42dd6665713726c38b63157a0ae1734f2030ae83444cfc446d"

      define_method(:install) do
        bin.install "duckmigrate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrfoh/duckmigrate/releases/download/v1.0.0-rc-6/duckmigrate-v1.0.0-rc-6_darwin_arm64.tar.gz"
      sha256 "37916e3470046722dbfd69bca9cb4d8daa5d749a9348881634d3e3677c792b75"

      define_method(:install) do
        bin.install "duckmigrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrfoh/duckmigrate/releases/download/v1.0.0-rc-6/duckmigrate-v1.0.0-rc-6_linux_amd64.tar.gz"
      sha256 "09f22041c875cad54907bb975bb930ade40b2c88f7f5bc477b29852b5f27d0b9"
      define_method(:install) do
        bin.install "duckmigrate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrfoh/duckmigrate/releases/download/v1.0.0-rc-6/duckmigrate-v1.0.0-rc-6_linux_arm64.tar.gz"
      sha256 "80b9734531828378b37899bf8b63c2a2cf6705fcd100835625ba822e850a5afa"
      define_method(:install) do
        bin.install "duckmigrate"
      end
    end
  end

  test do
    system "#{bin}/duckmigrate", "--version"
  end
end
