# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Httpprobe < Formula
  desc "A powerful HTTP API testing tool for defining, running, and validating API tests using YAML or JSON"
  homepage "https://github.com/mrfoh/httpprobe"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrfoh/httpprobe/releases/download/v1.3.0/httpprobe-v1.3.0_darwin_amd64.tar.gz"
      sha256 "ac085731a0dcb64f465275ca69844079e362ed15337b89742121324e8f68a995"

      define_method(:install) do
        bin.install "httpprobe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrfoh/httpprobe/releases/download/v1.3.0/httpprobe-v1.3.0_darwin_arm64.tar.gz"
      sha256 "97665eda94b0c6a554bbf529f27d82fa003568cb56437a15bfaeba2d7420164b"

      define_method(:install) do
        bin.install "httpprobe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrfoh/httpprobe/releases/download/v1.3.0/httpprobe-v1.3.0_linux_amd64.tar.gz"
      sha256 "7b34b10aebbe0790dcb32825e5a6ed97825a1418754e91da8242bf806152de58"
      define_method(:install) do
        bin.install "httpprobe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrfoh/httpprobe/releases/download/v1.3.0/httpprobe-v1.3.0_linux_arm64.tar.gz"
      sha256 "314945c1fdac687cf9aa7a122a280d9caf1a1a142ebdc7e33380c1496d93d3fd"
      define_method(:install) do
        bin.install "httpprobe"
      end
    end
  end

  test do
    system "#{bin}/httpprobe", "--version"
  end
end
