# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Httpprobe < Formula
  desc "A powerful HTTP API testing tool for defining, running, and validating API tests using YAML or JSON"
  homepage "https://github.com/mrfoh/httpprobe"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrfoh/httpprobe/releases/download/v1.2.0/httpprobe-v1.2.0_darwin_amd64.tar.gz"
      sha256 "1e52e41739f5715b38c0b57fc61f46f87997f769370448c875ed35fe29f1a3ba"

      define_method(:install) do
        bin.install "httpprobe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrfoh/httpprobe/releases/download/v1.2.0/httpprobe-v1.2.0_darwin_arm64.tar.gz"
      sha256 "d6bbd0d0e63d75ce26c5c8231d386f83e639a48a35a1a4e34e4ec2838ba108cc"

      define_method(:install) do
        bin.install "httpprobe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrfoh/httpprobe/releases/download/v1.2.0/httpprobe-v1.2.0_linux_amd64.tar.gz"
      sha256 "f29456371fde06e7892e1f6f11f00f63d4d63a64717e73c268036b4dfa40bbb3"
      define_method(:install) do
        bin.install "httpprobe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrfoh/httpprobe/releases/download/v1.2.0/httpprobe-v1.2.0_linux_arm64.tar.gz"
      sha256 "38da69510db5a9246e6bdf906797d8e30a3327de4c09882383af56af5b30fab4"
      define_method(:install) do
        bin.install "httpprobe"
      end
    end
  end

  test do
    system "#{bin}/httpprobe", "version"
  end
end
