# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Httpprobe < Formula
  desc "A powerful HTTP API testing tool for defining, running, and validating API tests using YAML or JSON"
  homepage "https://github.com/mrfoh/httpprobe"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrfoh/httpprobe/releases/download/v1.1.1/httpprobe-v1.1.1_darwin_amd64.tar.gz"
      sha256 "6a08ae6e1ee4fd41a8717a1cde5fe461167da664385f82c7e8f5b907f913a6c3"

      def install
        bin.install "httpprobe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrfoh/httpprobe/releases/download/v1.1.1/httpprobe-v1.1.1_darwin_arm64.tar.gz"
      sha256 "6a6bef3a2f02390a644359f174ebbe9df6467c8e12e2ed3075e658de497abb52"

      def install
        bin.install "httpprobe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mrfoh/httpprobe/releases/download/v1.1.1/httpprobe-v1.1.1_linux_amd64.tar.gz"
        sha256 "ea80ae04b54c747fc78321dab6d06240261c33f5096fc6fc6a1ebf284a21c67d"

        def install
          bin.install "httpprobe"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mrfoh/httpprobe/releases/download/v1.1.1/httpprobe-v1.1.1_linux_arm64.tar.gz"
        sha256 "a03e1854bc4bac1fc6c9ae71a2d93121fa2db4aae13fd71a832f8906b9da3a83"

        def install
          bin.install "httpprobe"
        end
      end
    end
  end

  test do
    system "#{bin}/httpprobe", "version"
  end
end
